Backend: Welcome to Lollipop

diff --git a/_archidroid/auto/system/xbin/ARCHIDROID_RUNONCE b/_archidroid/auto/system/xbin/ARCHIDROID_RUNONCE
--- a/_archidroid/auto/system/xbin/ARCHIDROID_RUNONCE
+++ b/_archidroid/auto/system/xbin/ARCHIDROID_RUNONCE
@@ -22,7 +22,8 @@
 # limitations under the License.
 
 ADMOUNTED() {
-	return "$(mount | grep -qi "$1"; echo $?)"
+	mount 2>&1 | grep -qi "$1"
+	return $?
 }
 
 # Initial variables, you should NOT change them unless you know what you're doing
@@ -30,6 +31,7 @@ AD="/data/media/0/ArchiDroid"
 ADSYS="/system/archidroid"
 ADDEV="$ADSYS/dev"
 ADTMPFS="$ADSYS/tmpfs"
+ADFIFO="$ADTMPFS/RunOnce.fifo"
 LOG="$AD/RunOnce.log" # "/dev/null" is no verbose
 ADSTATUS="$ADTMPFS/ARCHIDROID_RUNONCE_STATUS"
 
@@ -58,11 +60,12 @@ if [[ ! -f "$ADSTATUS" ]]; then
 	# debuggerd and init.d are executed in the nearly same moment, which may cause typical race condition here
 	# It's very likely that these childs will enter this segment in the same moment, we must stop it right here
 	# If we're not the lowest PID of all the PIDs from the same process, exit
-	if [[ "$(pidof "$(basename "$0")" | awk '{print $1}')" != "$$" ]]; then
+	if [[ "$(pidof "$(basename "$0")" | awk '{print $NF}')" != "$$" ]]; then
 		exit 0
 	fi
 	ARCHIDROID_INIT "START" "TMPFS"
 	echo "$$" > "$ADSTATUS"
+	mkfifo "$ADFIFO"
 else
 	ADSIGNAL="$(cat "$ADSTATUS")"
 	if [[ "$ADSIGNAL" = "FINISHED" ]]; then
@@ -76,27 +79,23 @@ else
 		# Something tried to execute already running init, double-execution?
 		exit 3
 	else
-		# Old PID is dead and didn't exit properly, allow that for now
-		echo "$$" > "$ADSTATUS"
+		# Old PID is dead and didn't exit properly, probably panic
+		exit 4
 	fi
 fi
 
 # Parse args to variables
 BACKGROUND=0
-FORCEDSEMAPHORE=0
 for ARG in "$@"; do
 	case "$ARG" in
 		--background|background) BACKGROUND=1 ;;
-		--force|force) FORCEDSEMAPHORE=1 ;;
 	esac
 done
 
 # Now we need to make sure that this is a background process to prevent slowing down bootup
 if [[ "$BACKGROUND" -ne 1 ]]; then
-	# We're not running in background, let's start a child and tell him that he's running in background
 	echo "RESTART" > "$ADSTATUS"
-	"$0" "background" "$@" &
-	# Nothing to do here anymore, exit call
+	"$0" "--background" "$@" &
 	exit 0
 fi
 
@@ -107,23 +106,23 @@ fi
 exec 1>"$LOG"
 exec 2>&1
 
-date
-echo "ArchiDroid $(getprop ro.archidroid.version)"
-uname -a
-echo "INFO: ArchiDroid_RunOnce executed!"
+echo "$(date +"%F %T") INFO: ArchiDroid_RunOnce executed!"
+echo "$(date +"%F %T") INFO: ArchiDroid $(getprop ro.archidroid.version)"
+echo "$(date +"%F %T") INFO: $(cat /proc/version)"
 
-echo "INFO: Waiting for Zygote..."
+echo "$(date +"%F %T") INFO: Waiting for Zygote..."
+
 LOOP=0
-while [[ "$LOOP" -lt 10 && "$(pgrep zygote >/dev/null 2>&1; echo $?)" -ne 0 ]]; do
+while [[ "$LOOP" -lt 10 ]] &&  ! pgrep zygote >/dev/null 2>&1; do
 	((LOOP++))
 	sleep 1
 done
 
-if [[ "$(pgrep zygote >/dev/null 2>&1; echo $?)" -ne 0 ]]; then
-	echo "INFO: Zygote didn't spawn in given period, aborting backend!"
+if ! pgrep zygote >/dev/null 2>&1; then
+	echo "$(date +"%F %T") INFO: Zygote didn't spawn in given period, aborting backend!"
 	exit 1
 else
-	echo "INFO: Zygote spawned!"
+	echo "$(date +"%F %T") INFO: Zygote spawned!"
 fi
 
 DBUPDATE() {
@@ -149,12 +148,12 @@ DBUPDATE() {
 			if [[ "$VAL1" = "$VAL2" ]]; then
 				# Looks good
 				if [[ "$TRY" -gt 1 ]]; then
-					echo "INFO: DBUPDATE APPEND SUCCEEDED with $*. It was our $TRY try"
+					echo "$(date +"%F %T") INFO: DBUPDATE APPEND SUCCEEDED with $*. It was our $TRY try"
 				fi
 				return 0
 			else
 				# We failed
-				echo "WARNING: DBUPDATE APPEND FAILED with $*. This is our $TRY try"
+				echo "$(date +"%F %T") WARNING: DBUPDATE APPEND FAILED with $*. This is our $TRY try"
 				sleep 1
 			fi
 		else
@@ -177,17 +176,17 @@ DBUPDATE() {
 			if [[ "$VAL1" = "$3" ]]; then
 				# Value exists and is the same as the one we want to insert, that's great!
 				if [[ "$TRY" -gt 1 ]]; then
-					echo "INFO: DBUPDATE APPEND SUCCEEDED with $*. It was our $TRY try"
+					echo "$(date +"%F %T") INFO: DBUPDATE APPEND SUCCEEDED with $*. It was our $TRY try"
 				fi
 				return 0
 			else
 				# Oops, something gone wrong
-				echo "WARNING: DBUPDATE FAILED with $*. This is our $TRY try"
+				echo "$(date +"%F %T") WARNING: DBUPDATE FAILED with $*. This is our $TRY try"
 				sleep 1
 			fi
 		fi
 	done
-	echo "ERROR: Could not update $* after $TRY times. I'm giving up here, please investigate!"
+	echo "$(date +"%F %T") ERROR: Could not update $* after $TRY times. I'm giving up here, please investigate!"
 	return 1
 }
 
@@ -198,29 +197,19 @@ DBUPDATE() {
 # | |___| (_) || |  |  __/
 #  \____|\___/ |_|   \___|
 #
-# Which mode are we using?
-# 0 - Sammy
-# 1 - CyanogenMod
-# 2 - Omni
-ROM=0 # Default to sammy
-if [[ "$(grep -qi "ro.cm.version" "/system/build.prop"; echo $?)" -eq 0 ]]; then
-	ROM=1 # OK, definitely CM
-elif [[ "$(grep -qi "ro.omni.version" "/system/build.prop"; echo $?)" -eq 0 ]]; then
-	ROM=2 # OK, definitely Omni
-fi
 
 # Custom boot sound support
-if [[ -f "$AD/PowerOn.wav" && ! -z "$(which tinyplay)" ]]; then
+if [[ -f "$AD/PowerOn.wav" && -n "$(which tinyplay)" ]]; then
 	tinyplay "$AD/PowerOn.wav" >/dev/null 2>&1 &
 fi
 
 # Don't force install mode, unless FORCE file exists
 if [[ -f "$AD/FORCE" ]]; then
-	echo "WARNING: Forcing Install mode, even if Update mode found!"
 	FORCE=1
+	echo "$(date +"%F %T") WARNING: Forcing Install mode"
 else
-	echo "INFO: Not forcing Install mode if Update mode found"
 	FORCE=0
+	echo "$(date +"%F %T") INFO: Normal mode"
 fi
 
 # Let's find out what we want from our RunOnce
@@ -228,29 +217,27 @@ ADRELOAD=0
 ADMANY=0
 
 if [[ -f "$AD/INSTALL" || "$FORCE" -eq 1 ]]; then
-	echo "INFO: Install mode detected, I'm either after full wipe or forced to think so. Turning on ADMANY and DBUPDATE"
+	echo "$(date +"%F %T") INFO: Install mode detected"
 	if [[ -d "$AD/FIRSTBOOT/DATA" ]]; then
-		# Okay, this one is complicated due to lack of process substitution in our shell
-		# We set as ADMANY the output of a command created in named pipe
-		# This is because child shell can't modify parent's variables
-		ADMANY="$(
-			find "$AD/FIRSTBOOT/DATA" -mindepth 1 -maxdepth 1 -type d | (while read FOLDER; do
-				((ADMANY++))
+		(
+			mADMANY="$ADMANY"
+			find "$AD/FIRSTBOOT/DATA" -mindepth 1 -maxdepth 1 -type d | while read FOLDER; do
+				((mADMANY++))
 			done
-			echo "$ADMANY")
-		)"
+			echo "$mADMANY" > "$ADFIFO"
+		) &
+		ADMANY="$(cat "$ADFIFO")"
 	fi
-	echo "INFO: I found $ADMANY folders for merging (data) in total"
+	echo "$(date +"%F %T") INFO: Found $ADMANY folders for data merging"
 	DBUPDATE=1
-	ADRELOAD=1
 elif [[ -f "$AD/UPDATE" ]]; then
-	echo "INFO: Update mode detected. Turning off ADMANY and DBUPDATE"
+	echo "$(date +"%F %T") INFO: Update mode detected. Turning off ADMANY and DBUPDATE"
 	DBUPDATE=0
 else
 	# Panic
-	echo "FATAL ERROR: Could not detect Install/Update mode, ABORTING RUNONCE, PLEASE INVESTIGATE"
+	echo "$(date +"%F %T") ERROR: Could not detect Install/Update mode, ABORTING RUNONCE, PLEASE INVESTIGATE"
 	echo "FINISHED" > "$ADSTATUS"
-	setsid ARCHIDROID_INIT "background" &
+	ARCHIDROID_INIT "--background" &
 	exit 2
 fi
 
@@ -265,115 +252,87 @@ fi
 # ArchiDroid Semaphore
 # Wait until we see some android processes to consider boot is more or less complete (initial idea thanks to AndiP71)
 # Also respect number of loops, maybe something went wrong
-echo "INFO: RunOnce Semaphore started"
+echo "$(date +"%F %T") INFO: RunOnce Semaphore started"
 LOOP=0
-while ( ! pgrep com.android.systemu >/dev/null 2>&1 && [[ "$LOOP" -lt 600 ]]) || [[ "$FORCEDSEMAPHORE" -eq 1 ]] ; do
+until [[ "$LOOP" -ge 600 ]] || pgrep com.android.systemui >/dev/null 2>&1; do
 	((LOOP++))
 	if [[ "$DBUPDATE" -eq 1 ]]; then
 		if [[ -f /data/data/com.android.providers.settings/databases/settings.db ]]; then
-			echo "INFO: settings.db created! Performing DBUPDATE"
+			echo "$(date +"%F %T") INFO: settings.db created! Performing DBUPDATE"
 
-			# Let's update selected keyboard according to our choice
-			# TODO: We should handle this internally, according to FIRSTBOOT instead of hardcoding keyboards
-			ONESHOT=1
-			for KEYBOARDFULL in "org.pocketworkstation.pckeyboard/.LatinIME"; do
-				KEYBOARD="$(echo $KEYBOARDFULL | cut -d '/' -f 1)"
-				if [[ -d "/data/data/$KEYBOARD" && "$ONESHOT" -eq 1 ]]; then
-					echo "INFO: $KEYBOARD Keyboard found!"
-					DBUPDATE secure default_input_method "$KEYBOARDFULL"
-					DBUPDATE secure enabled_input_methods "$KEYBOARDFULL"
-					ONESHOT=0
-				elif [[ -d "/data/data/$KEYBOARD" ]]; then
-					echo "INFO: Additional $KEYBOARD Keyboard found!"
-					#DBUPDATE secure enabled_input_methods "$KEYBOARDFULL" APPEND ":"
-				fi
-			done
-
-			DBUPDATE secure advanced_reboot 1
-			DBUPDATE global transition_animation_scale 0.5
+			# Faster animations
 			DBUPDATE global animator_duration_scale 0.5
+			DBUPDATE global transition_animation_scale 0.5
 			DBUPDATE global window_animation_scale 0.5
-			DBUPDATE global wifi_scan_always_enabled 0
-			DBUPDATE global install_non_market_apps 1
-			DBUPDATE global development_settings_enabled 1
-			DBUPDATE global adb_enabled 0
 
-			if [[ "$ROM" -eq 0 ]]; then
-				# Samsung
-				echo "INFO: Applying Samsung-specific DBUPDATE"
-				DBUPDATE system lockscreen_ripple_effect 0
-				DBUPDATE system screen_mode_automatic_setting 0
-				DBUPDATE system screen_mode_setting 2
-				DBUPDATE system security_update_db 1
-				# Requires ROM Control
-				DBUPDATE system screen_off_anim_toggle 2
-				DBUPDATE system status_bar_traffic 0
-				DBUPDATE system battery_icon_list 4
-			elif [[ "$ROM" -eq 1 ]]; then
-				# CyanogenMod
-				echo "INFO: Applying CyanogenMod-specific DBUPDATE"
-				DBUPDATE system status_bar_battery 2
-				DBUPDATE system status_bar_battery_show_percent 1
-				DBUPDATE system screen_animation_style 1
-			elif [[ "$ROM" -eq 2 ]]; then
-				# OmniROM
-				echo "INFO: Applying OmniROM-specific DBUPDATE"
-				DBUPDATE system screen_off_animation 0
-				DBUPDATE system screenshot_in_power_menu 1
-				DBUPDATE system clear_recents_button 1
-				DBUPDATE system clear_recents_button_location 3
-				DBUPDATE system status_bar_battery_style 4
-				DBUPDATE system qs_smart_pulldown 1
-				DBUPDATE system volume_music_control 1
-			fi
+			# Circle battery
+			DBUPDATE system status_bar_battery_style 2 # Circle icon
+			DBUPDATE system status_bar_show_battery_percent 1 # Text inside the icon
+
+			# General fixes
+			DBUPDATE global development_settings_enabled 1 # Enable development settings
+			DBUPDATE global wifi_scan_always_enabled 0 # Disable wi-fi scanning
+			DBUPDATE secure advanced_reboot 1 # Enable advanced reboot
+			DBUPDATE secure button_backlight_timeout 1000 # Set backlight timeout to 1 second
+			DBUPDATE secure install_non_market_apps 1 # Allow installing APKs from unknown sources
 
 			# And don't execute twice
-			echo "INFO: Finished DBUPDATE"
+			echo "$(date +"%F %T") INFO: Finished DBUPDATE"
 			DBUPDATE=0
 		fi
 	fi
 
 	# Now let's MAKE SURE that our settings are in fact applied, only if we don't have shared_prefs already (prevent non-clean override)
 	if [[ "$ADMANY" -gt 0 ]]; then
-		# We need to use the same trick here as well
-		ADMANY="$(
-			find "$AD/FIRSTBOOT/DATA" -mindepth 1 -maxdepth 1 -type d | (while read FOLDER; do
+		(
+			mADMANY="$ADMANY"
+			find "$AD/FIRSTBOOT/DATA" -mindepth 1 -maxdepth 1 -type d | while read FOLDER; do
 				FOLDERSHORT="$(basename "$FOLDER")"
 				if [[ -d "/data/data/$FOLDERSHORT" ]]; then
-					#echo "INFO: I'm currently merging $FOLDERSHORT"
+
+					echo "$(date +"%F %T") INFO: Merging settings for $FOLDER"
+
+					# Firstly, copy recursive everything i
+					find "$FOLDER" -mindepth 1 -maxdepth 1 | while read TOCOPY; do
+						cp -R "$TOCOPY" "/data/data/$FOLDERSHORT/"
+					done
+
 					ADOWNER="$(busybox ls -ld "/data/data/$FOLDERSHORT" | awk '{print $3}')"
-					cp -R "$FOLDER"/* "/data/data/$FOLDERSHORT/"
 					busybox chown -hR "$ADOWNER.$ADOWNER" "/data/data/$FOLDERSHORT"
 
-					# Let's try to apply proper permissions, Android will correct them anyway later
+					# Apply permissions for folders
 					find "/data/data/$FOLDERSHORT" -type d -mindepth 1 | while read mFOLDER; do
 						case "$(basename "$mFOLDER")" in # This will match filenames
 							*) chmod 771 "$mFOLDER"
 						esac
 					done
+
+					# Apply permissions for files
 					find "/data/data/$FOLDERSHORT" -type f -mindepth 1 | while read mFILE; do
-						#case "$(echo "$mFILE" | awk -F '.' '{print $NF}')" in # This will match extensions, like jar
-							#"jar") chmod 664 "$mFILE" ;;
-							#*) chmod 660 "$mFILE"
-						#esac
+	#					case "$(echo "$mFILE" | awk -F '.' '{print $NF}')" in # This will match extensions, like jar
+	#						"jar") chmod 664 "$mFILE" ;;
+	#						*) chmod 660 "$mFILE"
+	#					esac
 						case "$(basename "$mFILE")" in # This will match filenames
-							"XposedBridge.jar") chmod 664 "$mFILE" ;;
+	#						"XposedBridge.jar") chmod 664 "$mFILE" ;;
 							*) chmod 660 "$mFILE"
 						esac
 					done
 
 					# And we're done!
 					rm -rf "$FOLDER"
-					((ADMANY--))
-					#echo "INFO: Done! $ADMANY to go"
+					((mADMANY--))
+					echo "$(date +"%F %T") INFO: Merging done! $ADMANY to go"
+					echo "$mADMANY" > "$ADFIFO"
+					exit 0
 				fi
 			done
-			echo "$ADMANY")
-		)"
+			echo "$mADMANY" > "$ADFIFO"
+		) &
+		ADMANY="$(cat "$ADFIFO")"
 	fi
 
 	# Sleeping time
-	FORCEDSEMAPHORE=0
 
 	if [[ "$LEDS" -ge 1 ]]; then
 		while :; do
@@ -420,39 +379,30 @@ while ( ! pgrep com.android.systemu >/dev/null 2>&1 && [[ "$LOOP" -lt 600 ]]) ||
 done
 
 if [[ "$LOOP" -ge 600 ]]; then
-	echo "ERROR: I looped $LOOP times and needed to exit from infinite loop, not good (RunOnce Semaphore)"
-elif [[ "$LOOP" -eq 0 ]]; then
-	echo "ERROR: I didn't even entered semaphore, forcing it this time, it may cause unexpected behaviour!"
-	echo "RESTART" > "$ADSTATUS"
-	"$0" "background" "forcedsemaphore" &
-	exit 3
+	echo "$(date +"%F %T") WARNING: I looped $LOOP times and needed to exit from infinite loop, not good (RunOnce Semaphore)"
 else
-	echo "INFO: I looped $LOOP times and didn't have to exit from infinite loop, that's nice (RunOnce Semaphore)"
-fi
-
-if [[ ! -z "$(getprop ro.build.selinux)" && -f /file_contexts ]]; then
-	echo "INFO: Found SELinux build, relabeling /data"
-	restorecon -R /data
+	echo "$(date +"%F %T") INFO: I looped $LOOP times and didn't have to exit from infinite loop, that's nice (RunOnce Semaphore)"
 fi
 
 # I'm runonce script so let's clean everything and delete myself
-rm -f "$AD/INSTALL" "$AD/UPDATE" "$AD/FORCE"
+rm -f "$ADFIFO" "$AD/INSTALL" "$AD/UPDATE" "$AD/FORCE"
 rm -rf "$AD/FIRSTBOOT"
+
+# Turn on the lights
+ARCHIDROID_INIT "--background" &
+
+# Finish
+echo "FINISHED" > "$ADSTATUS"
+echo "$(date +"%F %T") INFO: ArchiDroid RunOnce finished"
 
 # Execute a reboot if we need it
 if [[ "$ADRELOAD" -eq 1 ]]; then
-	echo "INFO: Reboot required, I'm rebooting the device right now"
-	setsid ARCHIDROID_INIT "background" &
-	sleep 1
-	if [[ -f "$ADSYS/system/reboot.wav" && ! -z "$(which tinyplay)" ]]; then
+	echo "$(date +"%F %T") INFO: Reboot required, I'm rebooting the device right now"
+	if [[ -f "$ADSYS/system/reboot.wav" && -n "$(which tinyplay)" ]]; then
 		tinyplay "$ADSYS/system/reboot.wav" >/dev/null 2>&1 &
 	fi
 	setprop ctl.restart surfaceflinger
 	setprop ctl.restart zygote
 fi
 
-# Finish
-echo "FINISHED" > "$ADSTATUS"
-echo "INFO: ArchiDroid RunOnce finished"
-date
 exit 0
