Experimental: Fix tethering 1. ARCHIDROID_CRON is obsolete 2. Improve internal communication between ArchiDroid Backend, especially tethering 3. Tethering now informs ARCHIDROID_INIT about the event directly 4. ARCHIDROID_MONITOR_DNS is now part of ARCHIDROID_INIT, previously: ARCHIDROID_CRON 5. Misc improvements here and there

diff --git a/_archidroid/auto/system/xbin/ARCHIDROID_MONITOR_DNS b/_archidroid/auto/system/xbin/ARCHIDROID_MONITOR_DNS
--- a/_archidroid/auto/system/xbin/ARCHIDROID_MONITOR_DNS
+++ b/_archidroid/auto/system/xbin/ARCHIDROID_MONITOR_DNS
@@ -23,34 +23,35 @@
 
 AD="/data/media/0/ArchiDroid"
 ADSYS="/system/archidroid"
-ADPROC="$ADSYS/tmpfs"
-ADCRON="$ADPROC/cron"
-LOG="$AD/Cron.log"
-MONITORS_DIR="$ADCRON/monitors"
-ADSTATUS="$MONITORS_DIR/ARCHIDROID_MONITOR_DNS"
+ADTMPFS="$ADSYS/tmpfs"
+LOG="$AD/DNS.log"
+ADSTATUS="$ADTMPFS/ARCHIDROID_MONITOR_DNS"
 
-exec 1>>"$LOG"
+exec 1>"$LOG"
 exec 2>&1
-mkdir -p "$MONITORS_DIR"
 
 REGENERATE_RESOLV() {
-	echo "nameserver $DNS1" > "$ADPROC/resolv.conf.tmp"
-	echo "nameserver $DNS2" >> "$ADPROC/resolv.conf.tmp"
-	cat /system/etc/resolv.conf >> "$ADPROC/resolv.conf.tmp"
-	busybox chmod 644 "$ADPROC/resolv.conf.tmp"
-	mv "$ADPROC/resolv.conf.tmp" "$ADPROC/resolv.conf"
+	{
+		echo "nameserver $DNS1"
+		echo "nameserver $DNS2"
+		cat "/system/etc/resolv.conf"
+	} > "$ADTMPFS/resolv.conf"
 }
 
 MONITOR_DNS() {
 	DNS1="$(getprop net.dns1)"
 	DNS2="$(getprop net.dns2)"
-	local CURDNS1=""
-	local CURDNS2=""
+	REGENERATE_RESOLV
+	local CURDNS1="$DNS1"
+	local CURDNS2="$DNS2"
+	echo "$(date) Current DNSes: $DNS1, $DNS2"
 	while :; do
-		CURDNS1=$(getprop net.dns1)
-		if [ "$CURDNS1" != "$DNS1" ]; then
-			CURDNS2=$(getprop net.dns2)
-			echo "DNS_MONITOR: Detected DNS change, previous: $DNS1 $DNS2, current: $CURDNS1 $CURDNS2"
+		CURDNS1="$(getprop net.dns1)"
+		if [[ "$CURDNS1" != "$DNS1" ]]; then
+			CURDNS2="$(getprop net.dns2)"
+			echo "$(date) Detected DNS change!"
+			echo "$(date) Previous: $DNS1, $DNS2"
+			echo "$(date) Current: $CURDNS1, $CURDNS2"
 			DNS1="$CURDNS1"
 			DNS2="$CURDNS2"
 			REGENERATE_RESOLV
@@ -60,19 +61,25 @@ MONITOR_DNS() {
 	done
 }
 
-if [ -f "$ADSTATUS" ]; then
+echo "$(date) Active!"
+
+if [[ -f "$ADSTATUS" ]]; then
+	echo "$(date) Previous instance found, cleaning up..."
 	rm -f "$ADSTATUS"
-	sleep 1 # If there was a previous instance of the same monitor, give it a time to cleanup and finish
+	sleep 1 # Give it some time to cleanup and finish
 fi
 
-echo "DNS_MONITOR: Active! Current DNSes: $(getprop net.dns1) $(getprop net.dns2)"
+echo "$$" > "$ADSTATUS"
+trap 'kill $(jobs -p); rm -f "$ADSTATUS"' SIGINT SIGTERM EXIT
 
 MONITOR_DNS &
 
-mkdir -p "$MONITORS_DIR"
-echo "$$" > "$ADSTATUS"
-inotifywait -qq -e delete -e modify "$ADSTATUS"
-echo "DNS_MONITOR: Caught EXIT signal!"
-echo "DNS_MONITOR: Finishing..."; kill 0
+if [[ ! -z "$(which inotifywait)" ]]; then
+	inotifywait -qq -e delete -e modify "$ADSTATUS"
+else
+	wait # Fallback, should never happen
+fi
+
+echo "$(date) Shutting down..."
 
 exit 0
