SELinux: Round 1

diff --git a/_archidroid/auto/system/xbin/ARCHIDROID_INIT b/_archidroid/auto/system/xbin/ARCHIDROID_INIT
--- a/_archidroid/auto/system/xbin/ARCHIDROID_INIT
+++ b/_archidroid/auto/system/xbin/ARCHIDROID_INIT
@@ -21,15 +21,11 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-ADMOUNTED() {
-	mount 2>&1 | grep -qi "$1"
-	return $?
-}
-
 ADTWEAK() {
 	# $1 - what we're changing
 	# $2 - to what we're changing
-	local CURRENT="$(cat "$1")"
+	local CURRENT=""
+	CURRENT="$(cat "$1")"
 	if [[ "$CURRENT" = "$2" ]]; then
 		echo "$(date +"%F %T") INFO: ADTWEAK: Value of $1 is already set to $CURRENT"
 	else
@@ -39,13 +35,11 @@ ADTWEAK() {
 }
 
 ADEVENT() {
-	if [[ -p "$ADEVENTPIPE" ]]; then
-		if ! pidof ARCHIDROID_EVENT_LISTENER >/dev/null 2>&1; then
-			ADSTART "EVENT_LISTENER"
-			sleep 2
-		fi
-		echo "$@" > "$ADEVENTPIPE"
+	if ! pidof ARCHIDROID_EVENT_LISTENER >/dev/null 2>&1; then
+		ADSTART "EVENT_LISTENER"
+		sleep 2
 	fi
+	echo "$@" > "$ADEVENTS/Init.EVENT"
 }
 
 ADSTOP() {
@@ -90,9 +84,6 @@ ADSTOP() {
 			kill $(pidof logcat) >/dev/null 2>&1
 		;;
 		"TMPFS")
-			if ADMOUNTED "$ADTMPFS"; then
-				umount "$ADTMPFS"
-			fi
 		;;
 		archidroid_haveged)
 			kill $(pidof archidroid_haveged) >/dev/null 2>&1
@@ -132,36 +123,16 @@ ADSTART() {
 					# If adblock is currently deactivated, set proper DNSes
 					ADEVENT "CONNECTIVITY_CHANGE 0"
 
-					if ! cmp /system/archidroid/dev/spinners/_Hosts/Default /system/etc/hosts >/dev/null 2>&1; then
+					if ! cmp /system/archidroid/dev/spinners/_Hosts/NoAdBlocking /system/etc/hosts >/dev/null 2>&1; then
 						mount -o remount,rw /system
-
-						if [[ "$HOSTSLOCKED" -eq 1 ]]; then
-							chattr -i /system/etc/hosts
-						fi
-
-						cp -p /system/archidroid/dev/spinners/_Hosts/Default /system/etc/hosts
-
-						if [[ "$HOSTSLOCKED" -eq 1 ]]; then
-							chattr +i /system/etc/hosts
-						fi
-
+						cp -p /system/archidroid/dev/spinners/_Hosts/NoAdBlocking /system/etc/hosts
 						mount -o remount,ro /system
 					fi
 					ADSTART "archidroid_dnsmasq"
 				else
 					if ! cmp /system/archidroid/etc/hosts /system/etc/hosts >/dev/null 2>&1; then
 						mount -o remount,rw /system
-
-						if [[ "$HOSTSLOCKED" -eq 1 ]]; then
-							chattr -i /system/etc/hosts
-						fi
-
 						cp -p /system/archidroid/etc/hosts /system/etc/hosts
-
-						if [[ "$HOSTSLOCKED" -eq 1 ]]; then
-							chattr +i /system/etc/hosts
-						fi
-
 						mount -o remount,ro /system
 					fi
 				fi
@@ -215,10 +186,7 @@ ADSTART() {
 			fi
 		;;
 		"TMPFS")
-			if ! ADMOUNTED "$ADTMPFS"; then
-				mkdir -p "$ADTMPFS"
-				mount -t tmpfs tmpfs "$ADTMPFS"
-			fi
+			mkdir -p "$ADTMPFS"
 		;;
 		"archidroid_dnsmasq")
 			if [[ "$ADBLOCK" -eq 1 && "$ADBLOCK_PROXYDNS" -eq 1 ]]; then
@@ -236,14 +204,14 @@ ADSTART() {
 				else
 					cp -p "/system/etc/resolv.conf" "$ADTMPFS/resolv.conf"
 				fi
-				echo "$(date +"%F %T") INFO: ADBLOCK: Activated archidroid_dnsmasq - local DNS server on 127.0.0.1:53, forwarding clean non-blocked traffic to specified DNS servers"
 				archidroid_dnsmasq $EXTRA -C /system/archidroid/etc/dnsmasq.conf # Yes, we must break on spaces in this case
+				echo "$(date +"%F %T") INFO: ADBLOCK: Activated archidroid_dnsmasq - local DNS server on 127.0.0.1:53, forwarding clean non-blocked traffic to specified DNS servers"
 			fi
 		;;
 		"archidroid_pixelserv")
 			if [[ "$ADBLOCK" -eq 1 ]]; then
+				archidroid_pixelserv 127.0.0.1 &
 				echo "$(date +"%F %T") INFO: ADBLOCK: Activated archidroid_pixelserv - local web server on 127.0.0.1:80, responding with NULLGIF"
-				archidroid_pixelserv 127.0.0.1 >/dev/null 2>&1 &
 			fi
 		;;
 		"archidroid_haveged")
@@ -284,7 +252,6 @@ ADRELOAD() {
 			ADRELOAD "ADBLOCK"
 			ADRELOAD "LOGCAT"
 			;;
-		"HOSTSLOCKED") ADNOTIFY "$1" ;;
 		*)
 			ADSTOP "$1"
 			ADSTART "$1"
@@ -310,42 +277,87 @@ ADNOTIFY() {
 				ARCHIDROID_INIT "START" "ADBLOCK"
 			) &
 		;;
-		"HOSTSLOCKED")
-			mount -o remount,rw /system
-			if [[ "$HOSTSLOCKED" -eq 1 ]]; then
-				chattr +i /system/etc/hosts
-			else
-				chattr -i /system/etc/hosts
-			fi
-			mount -o remount,ro /system
-		;;
 	esac
+}
+
+DBUPDATE() {
+	# Thanks to idcrisis, modified by JustArchi
+	local TRY=0
+	local VAL1=""
+	local VAL2=""
+	local ID=""
+
+	while [[ "$TRY" -le 5 ]] ; do
+		((TRY++))
+		if [[ "$4" = "APPEND" ]]; then
+			# Append mode, value should exist already then
+			VAL1="$(sqlite3 /data/data/com.android.providers.settings/databases/settings.db "select value from $1 where name='$2';" 2>/dev/null)"
+			VAL1="$VAL1$5$3"
+
+			# Let's update it now
+			sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update $1 set value='$VAL1' where name='$2';" 2>/dev/null
+
+			# See if it worked
+			VAL2="$(sqlite3 /data/data/com.android.providers.settings/databases/settings.db "select value from $1 where name='$2';" 2>/dev/null)"
+
+			if [[ "$VAL1" = "$VAL2" ]]; then
+				# Looks good
+				if [[ "$TRY" -gt 1 ]]; then
+					echo "$(date +"%F %T") INFO: DBUPDATE APPEND SUCCEEDED with $*. It was our $TRY try"
+				fi
+				return 0
+			else
+				# We failed
+				echo "$(date +"%F %T") WARNING: DBUPDATE APPEND FAILED with $*. This is our $TRY try"
+				sleep 1
+			fi
+		else
+			# Insert/Update mode, check if value already exists
+			VAL1="$(sqlite3 /data/data/com.android.providers.settings/databases/settings.db "select value from $1 where name='$2';" 2>/dev/null)"
+			if [[ -z "$VAL1" ]]; then
+				# We don't have any value, insert mode
+				ID='null' # This actually means that we follow auto incremented key value and not putting our own
+				sqlite3 /data/data/com.android.providers.settings/databases/settings.db "insert into $1 values($ID, '$2', '$3');" 2>/dev/null
+			elif [[ "$VAL1" = "$3" ]]; then
+				# Value exists and is the same as the one we want to insert, that's great!
+				return 0
+			else
+				# Value exists but is not the one we want, update mode
+				sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update $1 set value='$3' where name='$2';" 2>/dev/null
+			fi
+
+			# See if it worked
+			VAL1="$(sqlite3 /data/data/com.android.providers.settings/databases/settings.db "select value from $1 where name='$2';" 2>/dev/null)"
+			if [[ "$VAL1" = "$3" ]]; then
+				# Value exists and is the same as the one we want to insert, that's great!
+				if [[ "$TRY" -gt 1 ]]; then
+					echo "$(date +"%F %T") INFO: DBUPDATE APPEND SUCCEEDED with $*. It was our $TRY try"
+				fi
+				return 0
+			else
+				# Oops, something gone wrong
+				echo "$(date +"%F %T") WARNING: DBUPDATE FAILED with $*. This is our $TRY try"
+				sleep 1
+			fi
+		fi
+	done
+	echo "$(date +"%F %T") ERROR: Could not update $* after $TRY times. I'm giving up here, please investigate!"
+	return 1
 }
 
 # Initial variables, you should NOT change them unless you know what you're doing
 AD="/data/media/0/ArchiDroid"
+ADEVENTS="/data/media/0/ArchiDroid/System/Events"
 ADSYS="/system/archidroid"
 ADDEV="$ADSYS/dev"
-ADTMPFS="$ADSYS/tmpfs"
-ADEVENTPIPE="$ADTMPFS/EVENTS"
+ADTMPFS="/dev/archidroid"
+ADFIFO="$ADTMPFS/Init.fifo"
 LOG="$AD/Init.log" # "/dev/null" is no verbose
-#RUNONCELOG="$AD/RunOnce.log" # Unused
 ADSTATUS="$ADTMPFS/ARCHIDROID_INIT_STATUS"
 
-# Exit if barebones preset was used
-if [[ -f "/system/archidroid/dev/PRESET_BAREBONES" ]]; then
+# Exit if there is no $AD folder, or barebones preset was used
+if [[ ! -d "$AD" || -f "/system/archidroid/dev/PRESET_BAREBONES" ]]; then
 	exit 0
-fi
-
-# Exit if user wiped data without reflashing
-if [[ ! -f "/data/ARCHIDROID_DONT_REMOVE_ME" ]] ; then
-	if ADMOUNTED "/data"; then
-		sync
-		reboot recovery || poweroff
-	else
-		# User is probably only charging his device, that's fine
-		exit 0
-	fi
 fi
 
 # Initial ArchiDroid dev status
@@ -380,12 +392,6 @@ if [[ "$(cat "$ADDEV/switches/Adblock")" = "Enabled" ]]; then
 	fi
 else
 	ADBLOCK=0
-fi
-
-if [[ "$(cat "$ADDEV/switches/HostsLocked")" = "Enabled" ]]; then
-	HOSTSLOCKED=1
-else
-	HOSTSLOCKED=0
 fi
 
 if [[ "$(cat "$ADDEV/switches/Logcat")" = "Enabled" ]]; then
@@ -466,12 +472,12 @@ exec 2>&1
 
 echo "$(date +"%F %T") INFO: ArchiDroid_Init executed!"
 echo "$(date +"%F %T") INFO: ArchiDroid $(getprop ro.archidroid.version)"
-echo "$(date +"%F %T") INFO: $(cat /proc/version)"
+cat /proc/version
 
 echo "$(date +"%F %T") INFO: Waiting for Zygote..."
 
 LOOP=0
-while [[ "$LOOP" -lt 10 ]] &&  ! pgrep zygote >/dev/null 2>&1; do
+while [[ "$LOOP" -lt 10 ]] && ! pgrep zygote >/dev/null 2>&1; do
 	((LOOP++))
 	sleep 1
 done
@@ -492,29 +498,74 @@ fi
 #
 
 # Bring su daemon if available
-if [[ -n "$(which daemonsu)" ]]; then
+if which daemonsu >/dev/null 2>&1; then
 	echo "$(date +"%F %T") INFO: SuperSU daemon found, calling daemonsu!"
 	daemonsu --auto-daemon &
 fi
 
+# Show LiveBoot if included
+if [[ -f /system/app/LiveBoot/LiveBoot.apk && ! -f "/data/data/eu.chainfire.liveboot/files/liveboot" ]]; then # But only if user didn't touch it yet
+	cp /system/bin/app_process32 /dev/.app_process_liveboot
+	chown 0:0 /dev/.app_process_liveboot
+	chmod 700 /dev/.app_process_liveboot
+	NO_ADDR_COMPAT_LAYOUT_FIXUP=1 ANDROID_ROOT=/system CLASSPATH=/system/app/LiveBoot/LiveBoot.apk /dev/.app_process_liveboot /system/bin eu.chainfire.liveboot.a.j /system/app/LiveBoot/LiveBoot.apk /system/app/LiveBoot/lib/arm/libcfsurface.so boot dark logcatlevels=VDIWEFS logcatbuffers=MSC logcatformat=brief dmesg=0-99 lines=80 wordwrap &
+	rm /dev/.app_process_liveboot
+fi
+
 # Custom boot sound support
-if [[ -f "$AD/PowerOn.wav" && -n "$(which tinyplay)" ]]; then
+if [[ -f "$AD/PowerOn.wav" ]] && which tinyplay >/dev/null 2>&1; then
 	tinyplay "$AD/PowerOn.wav" >/dev/null 2>&1 &
 fi
 
 # ArchiDroid Hardswap
-if busybox swapon --help 2>&1 | grep -qi "\-p pri"; then
-	HSEXTRA="-p 10"
+SWAP_BIN="swapon"
+SWAP_CMD="-p 1"
+if ! swapon 2>&1 | grep -qi "\-p pri"; then # If swapon doesn't support priority
+	if ! busybox swapon 2>&1 | grep -qi "\-p pri"; then # If busybox swapon doesn't support priority
+		SWAP_CMD="" # Disable priority
+	else
+		SWAP_BIN="busybox swapon" # Change binary to busybox swapon, as it supports priority
+	fi
 fi
 for HSPATH in "/cache" "/preload" "/storage/sdcard1" "/storage/extSdCard"; do
 	if [[ -f "$HSPATH/ArchiDroid.swp" ]]; then
 		echo "$(date +"%F %T") INFO: Found ArchiDroid swap file in $HSPATH directory, $(busybox du -mh "$HSPATH/ArchiDroid.swp" | awk '{print $1}')"
-		busybox swapon $HSEXTRA "$HSPATH/ArchiDroid.swp" # Yes, we must break on spaces in this case
+		$SWAP_BIN $SWAP_CMD "$HSPATH/ArchiDroid.swp"
 	fi
 done
 
 # ArchiDroid services
 ADSTART "ALL"
+
+ADRELOAD=0
+ADMANY=0
+DBUPDATE=0
+FIRSTBOOT=0
+
+if [[ -f "$AD/INSTALL" || -f "$AD/UPDATE" ]]; then
+	FIRSTBOOT=1
+	echo "$(date +"%F %T") NOTICE: This is first boot!"
+	# Don't force install mode, unless FORCE file exists
+	if [[ -f "$AD/INSTALL" || -f "$AD/FORCE" ]]; then
+		echo "$(date +"%F %T") INFO: Install mode"
+		mkfifo "$ADFIFO"
+		if [[ -d "$AD/FIRSTBOOT/DATA" ]]; then
+			(
+				find "$AD/FIRSTBOOT/DATA" -mindepth 1 -maxdepth 1 -type d | (while read FOLDER; do
+					((ADMANY++))
+				done
+				echo "$ADMANY" > "$ADFIFO")
+			) &
+			ADMANY="$(cat "$ADFIFO")"
+		fi
+		echo "$(date +"%F %T") INFO: Found $ADMANY folders for data merging"
+		DBUPDATE=1
+		ADRELOAD=1
+		setprop "persist.sys.root_access" "$(getprop persist.sys.root_access)" # This is required, as for some reason CM now reads the value from /data/property and not getprop()
+	else
+		echo "$(date +"%F %T") INFO: Update mode"
+	fi
+fi
 
 # ArchiDroid Semaphore
 # Wait until we see some android processes to consider boot is more or less complete (initial idea thanks to AndiP71)
@@ -523,6 +574,81 @@ echo "$(date +"%F %T") INFO: Init Semaphore started"
 LOOP=0
 while [[ "$LOOP" -lt 600 ]] && ! pgrep com.android.systemu >/dev/null 2>&1; do
 	((LOOP++))
+
+	if [[ "$DBUPDATE" -eq 1 ]]; then
+		if [[ -f /data/data/com.android.providers.settings/databases/settings.db ]]; then
+			echo "$(date +"%F %T") INFO: settings.db created! Performing DBUPDATE"
+
+			# Faster animations
+			DBUPDATE global animator_duration_scale 0.5
+			DBUPDATE global transition_animation_scale 0.5
+			DBUPDATE global window_animation_scale 0.5
+
+			# Circle battery
+			DBUPDATE system status_bar_battery_style 2 # Circle icon
+			DBUPDATE system status_bar_show_battery_percent 1 # Text inside the icon
+
+			# General fixes
+			DBUPDATE global development_settings_enabled 1 # Enable development settings
+			DBUPDATE global wifi_scan_always_enabled 0 # Disable wi-fi scanning
+			DBUPDATE secure advanced_reboot 1 # Enable advanced reboot
+			DBUPDATE secure button_backlight_timeout 1000 # Set backlight timeout to 1 second
+			DBUPDATE secure install_non_market_apps 1 # Allow installing APKs from unknown sources
+
+			# And don't execute twice
+			echo "$(date +"%F %T") INFO: Finished DBUPDATE"
+			DBUPDATE=0
+		fi
+	fi
+
+	if [[ "$ADMANY" -gt 0 ]]; then
+		(
+			find "$AD/FIRSTBOOT/DATA" -mindepth 1 -maxdepth 1 -type d | (while read FOLDER; do
+				FOLDERSHORT="$(basename "$FOLDER")"
+				if [[ -d "/data/data/$FOLDERSHORT" ]]; then
+
+					echo "$(date +"%F %T") INFO: Merging settings for $FOLDER"
+
+					# Firstly, copy recursive everything i
+					find "$FOLDER" -mindepth 1 -maxdepth 1 | while read TOCOPY; do
+						cp -R "$TOCOPY" "/data/data/$FOLDERSHORT/"
+					done
+
+					ADOWNER="$(busybox ls -ld "/data/data/$FOLDERSHORT" | awk '{print $3}')"
+					busybox chown -hR "$ADOWNER.$ADOWNER" "/data/data/$FOLDERSHORT"
+
+					# Apply permissions for folders
+					find "/data/data/$FOLDERSHORT" -type d -mindepth 1 | while read mFOLDER; do
+						case "$(basename "$mFOLDER")" in # This will match filenames
+							*) chmod 771 "$mFOLDER"
+						esac
+					done
+
+					# Apply permissions for files
+					find "/data/data/$FOLDERSHORT" -type f -mindepth 1 | while read mFILE; do
+	#					case "$(echo "$mFILE" | awk -F '.' '{print $NF}')" in # This will match extensions, like jar
+	#						"jar") chmod 664 "$mFILE" ;;
+	#						*) chmod 660 "$mFILE"
+	#					esac
+						case "$(basename "$mFILE")" in # This will match filenames
+	#						"XposedBridge.jar") chmod 664 "$mFILE" ;;
+							*) chmod 660 "$mFILE"
+						esac
+					done
+
+					# And we're done!
+					rm -rf "$FOLDER"
+					((ADMANY--))
+					echo "$(date +"%F %T") INFO: Merging done! $ADMANY to go"
+					echo "$ADMANY" > "$ADFIFO"
+					exit 0
+				fi
+			done
+			echo "$ADMANY" > "$ADFIFO")
+		) &
+		ADMANY="$(cat "$ADFIFO")"
+	fi
+
 	if [[ "$LEDS" -ge 1 ]]; then
 		while :; do
 			case "$LEDS" in
@@ -573,44 +699,29 @@ else
 	echo "$(date +"%F %T") INFO: I looped $LOOP times and didn't have to exit from infinite loop, that's nice (Init Semaphore)"
 fi
 
+if [[ "$FIRSTBOOT" -eq 1 ]]; then
+	rm -f "$ADFIFO" "$AD/INSTALL" "$AD/UPDATE" "$AD/FORCE"
+	rm -rf "$AD/FIRSTBOOT"
+fi
+
 # Execute a reboot if we need it
 if [[ -f "$AD/HARD_REBOOT_REQUIRED" ]]; then
 	echo "$(date +"%F %T") INFO: HARD_REBOOT_REQUIRED found, I'm rebooting device now..."
 	rm -f "$AD/SOFT_REBOOT_REQUIRED" "$AD/HARD_REBOOT_REQUIRED"
-	if [[ -f "$ADSYS/system/reboot.wav" && -n "$(which tinyplay)" ]]; then
+	if [[ -f "$ADSYS/system/reboot.wav" ]] && which tinyplay >/dev/null 2>&1; then
 		tinyplay "$ADSYS/system/reboot.wav" >/dev/null 2>&1
 	fi
 	sync
 	reboot
-elif [[ -f "$AD/SOFT_REBOOT_REQUIRED" ]]; then
+elif [[ "$ADRELOAD" -eq 1 || -f "$AD/SOFT_REBOOT_REQUIRED" ]]; then
 	echo "$(date +"%F %T") INFO: SOFT_REBOOT_REQUIRED found, I'm rebooting android interface now..."
 	rm -f "$AD/SOFT_REBOOT_REQUIRED"
-	if [[ -f "$ADSYS/system/reboot.wav" && -n "$(which tinyplay)" ]]; then
+	if [[ -f "$ADSYS/system/reboot.wav" ]] && which tinyplay >/dev/null 2>&1; then
 		tinyplay "$ADSYS/system/reboot.wav" >/dev/null 2>&1 &
 	fi
 	sync
 	setprop ctl.restart surfaceflinger
 	setprop ctl.restart zygote
-fi
-
-# Wait a little longer
-sleep 30
-
-####################################
-# We have fully loaded android now #
-####################################
-
-# Delete RunOnce if needed
-if [[ -n "$(which ARCHIDROID_RUNONCE)" ]]; then
-	echo "$(date +"%F %T") WARNING: RunOnce found, trying to remove it!"
-	mount -o remount,rw /system
-	rm -f "$(which ARCHIDROID_RUNONCE)" "$AD/ARCHIDROID_RUNONCE_STATUS"
-	if [[ -z "$(which ARCHIDROID_RUNONCE)" ]]; then
-		echo "$(date +"%F %T") INFO: Success!"
-		mount -o remount,ro /system
-	else
-		echo "$(date +"%F %T") ERROR: Failed!"
-	fi
 fi
 
 # Finish
